---
title: "Montreal weather functional data analysis"
author: "Prasham Bhuta and Evaldas Jankauskas"
date: '2022-05-25'
output:
  html_notebook:
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 5
    theme: lumen
---

```{r setup, include=FALSE}

# Upload libraries
library(fda)
library(fda.usc)
library(ggplot2)
library(data.table)
library(funFEM)
library(magrittr)
library(janitor)
library(RCurl)
library(demography)
library(far)

# Get and transform data
data("MontrealTemp")
dt <- data.table(MontrealTemp)
dt$year <- rownames(MontrealTemp)
dt <- melt.data.table(dt, id.vars = 'year')

dt[, `:=`(month = substr(variable, 0, 3))]
dt$month <- factor(x = dt$month, levels = c("jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"))
dt_lookup <- data.table(month = c("jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"),
                        month_num = c(1:12))
dt$month_num <- dt_lookup$month_num[match(dt$month, dt_lookup$month)]

# Create monthly average data
dt_mth <- dt[, .(avg = mean(value)), by = .(year, month_num)]
dt_mth$year %<>% as.numeric()

# Transform to long format
dt_mth_long <- dcast.data.table(data = dt_mth,
                                formula = month_num ~ year,
                                value.var = 'avg',
                                fun.aggregate = sum)

# Data for last 5 years
dt_mth_long_last5 <- dcast.data.table(data = dt_mth[year %in% seq(max(dt_mth$year)-4, max(dt_mth$year))],
                                      formula = month_num ~ year,
                                      value.var = 'avg',
                                      fun.aggregate = sum)
# Data without last 5 years
dt_mth_without_last5 <- dcast.data.table(data = dt_mth[year %in% seq(min(dt_mth$year), max(dt_mth$year)-4)],
                                      formula = month_num ~ year,
                                      value.var = 'avg',
                                      fun.aggregate = sum)
# Data without last 10 years
dt_mth_without_last10 <- dcast.data.table(data = dt_mth[year %in% seq(min(dt_mth$year), max(dt_mth$year)-9)],
                                         formula = month_num ~ year,
                                         value.var = 'avg',
                                         fun.aggregate = sum)

# Data for last 10 years
dt_mth_long_last10 <- dcast.data.table(data = dt_mth[year %in% seq(max(dt_mth$year)-9, max(dt_mth$year))],
                                       formula = month_num ~ year,
                                       value.var = 'avg',
                                       fun.aggregate = sum)

# Create matrix for monthly data: total, last 5 years and last 10 years
mt_temp_mth <- as.matrix(dt_mth_long[,-1])
mt_temp_mth_last5 <- as.matrix(dt_mth_long_last5[,-1])
mt_temp_mth_last10 <- as.matrix(dt_mth_long_last10[,-1])

# Create matrix for monthly data without last 5 years and without last 10 years
mt_temp_mth_minus_5 <- as.matrix(dt_mth_without_last5[,-1])
mt_temp_mth_minus_10 <- as.matrix(dt_mth_without_last10[,-1])

```

## Data exploration

```{r}
ggplot2::ggplot(data = dt, 
                aes(x = variable, 
                    y = value, 
                    color = year, 
                    group = year)) + 
  geom_line() +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  theme(legend.position="right") +
  labs(x = "Month and day", y = "Temperature in celcius", title = 'Temperature in Celsius in Montreal 1961-1994')
```

```{r}
ggplot2::ggplot(data = dt_mth, 
                aes(x = factor(month_num), 
                    y = avg, 
                    color = factor(year), 
                    group = year)) + 
  geom_line() +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  theme(legend.position="right") +
  labs(x = "Month",
       y = "Average temperature in celcius", 
       title = 'Monthly average temperature in Celsius in Montreal 1961-1994')
```

```{r}
ggplot(dt) + geom_boxplot(aes(x = month_num, 
                              y = value, 
                              group = month)) +
  labs(x = "Month", 
       y = "Temperature in celcius", 
       title = 'Temperature variation in Celsius in Montreal 1961-1994')
```

## Data smoothing

```{r smoothing}
mthRng  = c(0, 12)

# Define the harmonic acceleration operator
Lcoef        = c(0,(2*pi/diff(mthRng))^2,0)
harmaccelLfd = vec2Lfd(Lcoef, mthRng)

# Parameters for manual testing
mthbasis_test = create.fourier.basis(rangeval = mthRng, 
                                     nbasis = 10)
mthbasis = create.fourier.basis(rangeval = mthRng, 
                                nbasis = 10)
lambda_big <- 1
fdParobj_big <- fdPar(mthbasis, harmaccelLfd, lambda_big)
lambda_small <- 0.001
fdParobj_small <- fdPar(mthbasis, harmaccelLfd, lambda_small)

# Lambda big
temp_mth_fd_big = smooth.basis(y = mt_temp_mth, 
                               fdParobj = fdParobj_big)
plot(temp_mth_fd_big, 
     xlab = 'Month', 
     ylab = 'Average monthly temperature')

# Lambda small
temp_mth_fd_small = smooth.basis(y = mt_temp_mth, 
                                 fdParobj = fdParobj_small)
plot(temp_mth_fd_small, 
     xlab = 'Month', 
     ylab = 'Average monthly temperature')

# Create fda object

temp_mth_fdata_small <- fdata(temp_mth_fd_small$fd)
plot(temp_mth_fdata_small)
```

```{r, echo=FALSE, include=FALSE}
lambda     = 0.013
fdParobj   = fdPar(mthbasis, harmaccelLfd, lambda)
temp_mth_fd = smooth.basis(y = mt_temp_mth, 
                           fdParobj = fdParobj)
```


```{r}
# Optimal smoothing

# l <- seq(0.001,1,by = 0.001)
# nb <- seq(4, 12, by = 2)
# 
# set.seed(1234)
# temp_mth_param <- optim.basis(temp_mth_fdata, 
#                               numbasis = nb, 
#                               lambda = l)
# plot(temp_mth_param$fdata.est)
# temp_mth_param$gcv.opt
# temp_mth_param$lambda.opt
# temp_mth_param$numbasis.opt

# Smooth data with lambda that minimizes GCV
lambda <- 0.014
mthbasis <- create.fourier.basis(rangeval = mthRng, 
                                 nbasis = 12)

fdParobj   = fdPar(mthbasis, harmaccelLfd, lambda)

# Total period
temp_mth_fd = smooth.basis(y = mt_temp_mth, 
                           fdParobj = fdParobj)
#Period without last 5 years
temp_mth_fd_without_5 = smooth.basis(y=mt_temp_mth_minus_5,
                                     fdParobj = fdParobj)
#Period without last 10 years
temp_mth_fd_without_10 = smooth.basis(y=mt_temp_mth_minus_10,
                                     fdParobj = fdParobj)

plot(temp_mth_fd, xlab = 'Month', ylab = 'Average monthly temperature')

# Last 5 years
temp_mth_last5_fd = smooth.basis(y = mt_temp_mth_last5, 
                                 fdParobj = fdParobj)
plot(temp_mth_last5_fd, xlab = 'Month', ylab = 'Average monthly temperature')

# Last 10 years
temp_mth_last10_fd = smooth.basis(y = mt_temp_mth_last10, 
                                  fdParobj = fdParobj)
plot(temp_mth_last10_fd, xlab = 'Month', ylab = 'Average monthly temperature')

# Elementary pointwise mean and standard deviation

meantemp   = mean.fd(temp_mth_fd$fd)
stddevtemp = std.fd(temp_mth_fd$fd)

plot(temp_mth_fd, xlab = 'Month', ylab = 'Average monthly temperature')
lines(meantemp, lwd=4, lty=2, col=1)
lines(stddevtemp, lwd=4, lty=2, col=4)

# Create fda object

temp_mth_fdata <- fdata(temp_mth_fd$fd)
plot(temp_mth_fdata)

```

## Derivatives

```{r}
# First - velocity

temp_mth_d1 <- deriv.fd(temp_mth_fd$fd, 1)
plot(temp_mth_d1, xlab = "Month")

# Second - acceleration
temp_mth_d2 <- deriv.fd(temp_mth_fd$fd, 2)
plot(temp_mth_d2, xlab = "Month")

# phaseplanePlot(1, temp_mth_fd$fd)

#### Covariance

tempvarbifd <- var.fd(temp_mth_fd$fd)
# evaluate the variance-covariance surface and plot
mth <- seq(1,12,1)
tempvarmat <- eval.bifd(mth,mth,tempvarbifd)
# make a contour plot of the variance function
contour(mth, mth, tempvarmat,
        xlab="Month",
        ylab="Month",
        axes=TRUE)

```

## Principal component analysis

```{r}
nharm = 4
temp_mth_pcalist = pca.fd(temp_mth_fd$fd, nharm, centerfns = TRUE)

# attributes(temp_mth_pcalist)
# temp_mth_pcalist$harmonics

# plot(temp_mth_pcalist$harmonics)

plot.pca.fd(temp_mth_pcalist, harm = 1)
plot.pca.fd(temp_mth_pcalist, harm = 2)
plot.pca.fd(temp_mth_pcalist, harm = 3)
plot.pca.fd(temp_mth_pcalist, harm = 4)

# Rotate

temp_mth_rot_pcalist = varmx.pca.fd(temp_mth_pcalist)

plot.pca.fd(temp_mth_rot_pcalist, harm = 1)
plot.pca.fd(temp_mth_rot_pcalist, harm = 2)
plot.pca.fd(temp_mth_rot_pcalist, harm = 3)
plot.pca.fd(temp_mth_rot_pcalist, harm = 4)

```

## Clustering

```{r}
res <- funFEM(temp_mth_fd$fd, 
              K=4)

par(mfrow=c(1,2))
plot.fd(temp_mth_fd$fd, col=res$cls, lwd=2, lty=1)
fdmeans <- temp_mth_fd$fd
fdmeans$coefs <- t(res$prms$my)
plot(fdmeans, col=1:max(res$cls), lwd=2)

```

## Hypotheses testing

```{r}
source("./custom-functions/Ztest.R")
source("./custom-functions/Zboottest.R")
source("./custom-functions/trace.R")
source("./custom-functions/L2stat.R")
source("./custom-functions/trace.R")
source("./custom-functions/Fstat.R")

#### Last 5 years

# H0: mu(Last 5 year average) = mu(Total average)
# H1: mu(Last 5 year average) != mu(Total average)

# NaN values in coefficient matrix
dta <- temp_mth_last5_fd$fd
# dta

dta.coef <- remove_empty(dta$coefs, 
                         which = "cols", 
                         quiet = FALSE)
dta$fdnames$reps <- colnames(dta.coef)
dta.fd <- fd(dta.coef, 
             dta$basis, 
             dta$fdnames)
plot.fd(dta.fd, ylab = "Temperature")

t.sq <- seq(0,12, length = 61)
mean.total <- mean.fd(temp_mth_fd$fd)
mean_minus_5.total <- mean.fd(temp_mth_fd_without_5$fd)
mean_minus_10.total <- mean.fd(temp_mth_fd_without_10$fd)

# One sample pointwise t-test
```

```{r}
par(mar=c(1,1,1,1))
stat <- Z(x = dta.fd, 
          t.seq = t.sq, 
          mu = mean_minus_5.total)
```


```{r}
# One sample pointwise bootstrap t-test
par(mar=c(1,1,1,1))
stat_boot <- Z.boot(x = dta.fd, 
                    t.seq = t.sq, 
                    mu = mean_minus_5.total)
```

```{r}
# One sample L2_norm_based_test 

stat_l2_1 <- L2.stat(x = dta.fd, 
                     t.seq = t.sq, 
                     mu0 = mean_minus_5.total, 
                     replication = 500, 
                     method = 1)
stat_l2_1$statistics

stat_l2_1$pvalue
stat_l2_1$params$df

stat_l2_2 <- L2.stat(x = dta.fd, 
                     t.seq = t.sq, 
                     mu0 = mean_minus_5.total, 
                     replication = 500, 
                     method = 2)
stat_l2_2$statistics
stat_l2_2$pvalue
```

```{r}
# One sample F-type test 

stat_f1 <- F.stat(x = dta.fd, 
                  t.seq = t.sq, 
                  mu0 = mean_minus_5.total, 
                  replication = 500, 
                  method = 1)
stat_f1$statistics
stat_f1$pvalue
stat_f1$params$df1
stat_f1$params$df2

stat_f2 <- F.stat(x = dta.fd, 
                  t.seq = t.sq, 
                  mu0 = mean_minus_5.total, 
                  replication = 500, 
                  method=2)
stat_f2$statistics
stat_f2$pvalue
```

```{r}
#### Last 10 years

# H0: mu(Last 10 year average) = mu(Total average)
# H1: mu(Last 10 year average) != mu(Total average)

# NaN values in coefficient matrix
dta <- temp_mth_last10_fd$fd

dta.coef <- remove_empty(dta$coefs, 
                         which = "cols", 
                         quiet = FALSE)
dta$fdnames$reps <- colnames(dta.coef)
dta.fd <- fd(dta.coef, 
             dta$basis, 
             dta$fdnames)
plot(dta.fd)

t.sq <- seq(0,12, length = 61)

# One sample pointwise t-test
```

```{r}
stat <- Z(x = dta.fd, 
          t.seq = t.sq, 
          mu = mean_minus_10.total)
```


```{r}
# One sample pointwise bootstrap t-test

stat_boot <- Z.boot(x = dta.fd, 
                    t.seq = t.sq, 
                    mu = mean_minus_10.total)
```

```{r}
# One sample L2_norm_based_test 

stat_l2_1 <- L2.stat(x = dta.fd, 
                     t.seq = t.sq, 
                     mu0 = mean_minus_10.total, 
                     replication = 500, 
                     method = 1)
stat_l2_1$statistics
stat_l2_1$pvalue
stat_l2_1$params$df

stat_l2_2 <- L2.stat(x = dta.fd, 
                     t.seq = t.sq, 
                     mu0 = mean_minus_10.total, 
                     replication = 500, 
                     method = 2)
stat_l2_2$statistics
stat_l2_2$pvalue
stat_l2_2$params$df
```

```{r}
# One sample F-type test 

stat_f1 <- F.stat(x = dta.fd, 
                  t.seq = t.sq, 
                  mu0 = mean_minus_10.total, 
                  replication = 500, 
                  method = 1)
stat_f1$statistics
stat_f1$pvalue
stat_f1$params$df1
stat_f1$params$df2

stat_f2 <- F.stat(x = dta.fd, 
                  t.seq = t.sq, 
                  mu0 = mean_minus_10.total, 
                  replication = 500, 
                  method=2)
stat_f2$statistics
stat_f2$pvalue

```

## Functional time series

```{r}
# Such curves cannot be treated as being independent with the same distribution; they do not form a simple random sample of curves
# Temperature on a given day will be affected by temperature on previous day, so the curves will be dependent

dt_mth %<>% data.table()
dt_mth <- dt_mth[order(year, month_num)]
ts.monthly <- ts(dt_mth$avg, start = 1961, frequency = 12)

ftemp <- far::as.fdata(ts.monthly, 
                       col = 1, 
                       p = 12, 
                       dates = 1961:1994, 
                       name = "Average temperature")
ftemp

multplot(ftemp$"Average temperature", 
         type = "l")
```

```{r}
model1 <- far(data=ftemp, 
              y="Average temperature", 
              center=TRUE, 
              na.rm=FALSE)
coef.far(model1)
plot(model1)
names(model1)
```

```{r}
source('./custom-functions/predict_far2.R')
pred <- predict.far2(model1, newdata = ftemp, label = 1962:1995)
multplot(pred$"Average temperature", type = "l")
```

```{r}
pred1 <- predict.far2(model1, newdata = select.fdata(ftemp,date=1:33), label = 1962:1994)
# Real values
real1 <- select.fdata(ftemp,date=2:34)

errors1 <- pred1[[1]]-real1[[1]]
matplot(errors1, type = "l")
```

```{r}
summary(errors1)
apply(errors1, 2, function(x) sqrt(sum(x^2)))
```

```{r}
model2.cv <- far.cv(data=ftemp, y="Average temperature", ncv=2,
                    cvcrit = "Average temperature",
                    center=TRUE, na.rm = FALSE)
print(model2.cv)
```

```{r}
k2 <- model2.cv$minL2[1]

model2 <- far(data=ftemp, y="Average temperature", kn=k2,
              center=TRUE, na.rm=FALSE)
print(model2)
coef.far(model2)
```

```{r}
plot(model2)
```

```{r}
pred2 <- predict.far2(model2, newdata = ftemp, label = 1962:1995)
multplot(pred$"Average temperature", type = "l")
```

```{r}
pred2 <- predict.far2(model2, newdata = select.fdata(ftemp,date=1:33), label = 1962:1994)
errors2 <- pred2[[1]]-real1[[1]]
matplot(errors2, type = "l")
```

```{r}
summary(errors2)
apply(errors2, 2, function(x) sqrt(sum(x^2)))
apply(errors1, 2, function(x) sqrt(sum(x^2)))
```

```{r}
###
basis <- create.polygonal.basis((0:11)/12)
mtemp <- matrix(ts.monthly, ncol=34)
colnames(mtemp) <- 1961:1994
ftemp2 <- smooth.basis((0:11)/12, mtemp, basis)
# plotfit.fd(mtemp, (0:11)/12, ftemp2$fd)

temp.pc <- pca.fd(ftemp2$fd, 1)
plot(temp.pc)
```

```{r}
# dev.new()
plot(model1)
```

```{r}
# dev.new()
plot(temp.pc$harmonics)
```

```{r}
vj <- temp.pc$harmonics$coefs/sqrt(sum(temp.pc$harmonics$coefs^2))
data.frame(model1$v[[1]], vj)

```

